/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package test_interfaces_visuales;

/**
 *
 * @author erick
 */
public class fieldUserName extends javax.swing.JFrame {

    /**
     * Creates new form ScreenLogin
     */
    public fieldUserName() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        strBienvenido = new javax.swing.JLabel();
        formUserLogin = new javax.swing.JPanel();
        sepFieldName = new javax.swing.JSeparator();
        fieldUserName = new javax.swing.JTextField();
        strInicaSesion = new javax.swing.JLabel();
        fieldUserPass = new javax.swing.JPasswordField();
        sepFieldPass = new javax.swing.JSeparator();
        btnLogin = new javax.swing.JButton();
        btnForgetPass = new javax.swing.JLabel();
        btnRegister = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(22, 23, 32));
        bg.setToolTipText("");
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        strBienvenido.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 24)); // NOI18N
        strBienvenido.setForeground(new java.awt.Color(255, 255, 255));
        strBienvenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        strBienvenido.setText("¡Bienvenido a ManageMoney!");
        bg.add(strBienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 800, -1));

        formUserLogin.setBackground(new java.awt.Color(28, 29, 40));
        formUserLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(56, 58, 67), 2, true));

        fieldUserName.setBackground(new java.awt.Color(28, 29, 40));
        fieldUserName.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 12)); // NOI18N
        fieldUserName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fieldUserName.setText("Nombre de usuario");
        fieldUserName.setToolTipText("Nombre de Usuario");
        fieldUserName.setBorder(null);
        fieldUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldUserNameActionPerformed(evt);
            }
        });

        strInicaSesion.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 14)); // NOI18N
        strInicaSesion.setForeground(new java.awt.Color(204, 204, 204));
        strInicaSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        strInicaSesion.setText("Inicia Sesión");

        fieldUserPass.setBackground(new java.awt.Color(28, 29, 40));
        fieldUserPass.setText("jPasswordField1");
        fieldUserPass.setBorder(null);

        btnLogin.setBackground(new java.awt.Color(253, 147, 1));
        btnLogin.setForeground(new java.awt.Color(0, 0, 0));
        btnLogin.setText("Iniciar Sesión");
        btnLogin.setToolTipText("");

        javax.swing.GroupLayout formUserLoginLayout = new javax.swing.GroupLayout(formUserLogin);
        formUserLogin.setLayout(formUserLoginLayout);
        formUserLoginLayout.setHorizontalGroup(
            formUserLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(strInicaSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formUserLoginLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(formUserLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formUserLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(sepFieldName)
                        .addComponent(fieldUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                        .addComponent(fieldUserPass)
                        .addComponent(sepFieldPass, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );
        formUserLoginLayout.setVerticalGroup(
            formUserLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formUserLoginLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(strInicaSesion)
                .addGap(18, 18, 18)
                .addComponent(fieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sepFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldUserPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sepFieldPass, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        bg.add(formUserLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 380, 210));

        btnForgetPass.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 14)); // NOI18N
        btnForgetPass.setForeground(new java.awt.Color(204, 204, 204));
        btnForgetPass.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnForgetPass.setText("Recuperar Constraseña");
        bg.add(btnForgetPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, 170, -1));

        btnRegister.setFont(new java.awt.Font("Plus Jakarta Sans Medium", 0, 14)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(204, 204, 204));
        btnRegister.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnRegister.setText("Crear una cuenta");
        bg.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 160, -1));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        bg.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, 10, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldUserNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fieldUserName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fieldUserName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fieldUserName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fieldUserName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fieldUserName().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel btnForgetPass;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel btnRegister;
    private javax.swing.JTextField fieldUserName;
    private javax.swing.JPasswordField fieldUserPass;
    private javax.swing.JPanel formUserLogin;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator sepFieldName;
    private javax.swing.JSeparator sepFieldPass;
    private javax.swing.JLabel strBienvenido;
    private javax.swing.JLabel strInicaSesion;
    // End of variables declaration//GEN-END:variables
}
